### ISSUE TITLE
in the footer add

### ISSUE THREAD

**Issue by owocki** [web3event-co/pluriverse.wtf#3]
"fork this book" https://drive.google.com/drive/folders/1__K_tTmJViz0ukN8dE9GmuXErsxrlOQO
"fund the pluriverse.wtf" - https://gitcoin.co/grants/7369/a-dao-for-the-pluriverse and https://yeet.daohaus.club/dao/0x64/0x06b109353f6f2b5c028b9493f0787127bc6e1560/1

**Comment by owocki** [comment]
@cristinalare could we add these links to the footer pls?

**Comment by cristinalare** [comment]
> @cristinalare could we add these links to the footer pls?

yes, sure
